name: Lint

on: 
  push: 
  pull_request:
  workflow_dispatch:
    inputs:
      tags:
        required: false

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install flake8
        run: pip install flake8
      - name: flake8 Lint
        uses: py-actions/flake8@v2
